name: Build & Deploy player-backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Player Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file ./player-backend/pom.xml

      - name: Build the application
        run: |
          mvn clean --file ./player-backend
          mvn -B package --file ./player-backend/pom.xml
          
