name: Build & Deploy player-backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Player Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file ./player-backend/pom.xml

      - name: Build the application
        run: |
          mvn clean --file ./player-backend
          mvn -B package --file ./player-backend/pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.PLAYER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./docker/backend/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/player-backend:latest