name: Build & Deploy player-backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Player Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file ./player-backend/pom.xml

      - name: Build the application
        run: |
          mvn clean --file ./player-backend
          mvn -B package --file ./player-backend/pom.xml

      - name: Extract Project Version
        id: extract_version
        run: |
          cd player-backend
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.PLAYER_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: player-backend
          file: docker/backend/Dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/player-backend:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKER_HUB_USERNAME }}/player-backend:latest